import type { SupabaseClient } from "@supabase/supabase-js";

import { isUuid } from "../matches/model";
import type { Database } from "../supabase/database.types";
import type { TeamAccessContext } from "../teams/context";
import type { PermissionCode } from "../teams/permissions";
import { validateCreateFinanceEntryPayload, validateFinanceEntryMutationPayload, validateMemberDuePayload } from "./validation";

const MAX_REQUEST_BYTES = 16 * 1024;
type Guard = (slug: string, permission: PermissionCode) => Promise<TeamAccessContext | null>;
export type FundsActionDependencies = { requireTeamPermission: Guard; supabase: Pick<SupabaseClient<Database>, "rpc"> };
function failure(status: number, code: string, message: string, fieldErrors?: Readonly<Record<string, string>>) { return Response.json({ ok: false, code, message, ...(fieldErrors ? { fieldErrors } : {}) }, { status }); }
function preflight(request: Request) {
  let sameOrigin = false;
  try { sameOrigin = request.headers.get("origin") === new URL(request.url).origin || (!request.headers.get("origin") && request.headers.get("sec-fetch-site") === "same-origin"); } catch { sameOrigin = false; }
  if (!sameOrigin) return failure(403, "forbidden", "Yêu cầu không được phép.");
  if (request.headers.get("content-type")?.split(";", 1)[0]?.trim().toLowerCase() !== "application/json") return failure(415, "content_type", "Định dạng yêu cầu không được hỗ trợ.");
  return null;
}
async function body(request: Request): Promise<{ ok: true; value: unknown } | { ok: false; response: Response }> {
  const declared = request.headers.get("content-length"); if (declared && /^\d+$/u.test(declared) && Number(declared) > MAX_REQUEST_BYTES) return { ok: false, response: failure(413, "too_large", "Yêu cầu quá lớn.") };
  try { const text = await request.text(); if (new TextEncoder().encode(text).byteLength > MAX_REQUEST_BYTES) return { ok: false, response: failure(413, "too_large", "Yêu cầu quá lớn.") }; return { ok: true, value: JSON.parse(text) }; } catch { return { ok: false, response: failure(400, "malformed", "Dữ liệu yêu cầu không hợp lệ.") }; }
}
async function defaults(): Promise<FundsActionDependencies> { const [{ requireTeamPermission }, { createServerSupabaseClient }] = await Promise.all([import("../teams/context"), import("../supabase/server")]); return { requireTeamPermission, supabase: await createServerSupabaseClient() }; }
function rpcFailure(error: { code?: string }) { switch (error.code) { case "40001": return failure(409, "stale", "Dữ liệu quỹ đã thay đổi. Vui lòng tải lại."); case "23505": return failure(409, "conflict", "Khoản quỹ đã tồn tại."); case "55000": return failure(409, "lifecycle", "Khoản quỹ không còn ở trạng thái cho phép."); case "42501": case "28000": return failure(403, "forbidden", "Bạn không có quyền quản lý quỹ đội."); case "P0002": return failure(404, "not_found", "Không tìm thấy khoản quỹ."); case "23503": case "23514": case "22023": return failure(422, "validation", "Dữ liệu quỹ không còn hợp lệ."); default: return failure(500, "server", "Không thể cập nhật quỹ đội. Vui lòng thử lại."); } }
async function input(request: Request) { const rejected = preflight(request); if (rejected) return { response: rejected } as const; const parsed = await body(request); return parsed.ok ? { value: parsed.value } as const : { response: parsed.response } as const; }
async function authorize(slug: string, supplied?: FundsActionDependencies) { const dependencies = supplied ?? await defaults(); const context = await dependencies.requireTeamPermission(slug, "finance.manage"); return { dependencies, context }; }
async function invoke(dependencies: FundsActionDependencies, name: "manage_finance_entry" | "manage_member_due", args: Record<string, unknown>, idKey: "entryId" | "dueId", status = 200) { const rpc = dependencies.supabase.rpc as unknown as (name: string, args: Record<string, unknown>) => Promise<{ data: unknown; error: { code?: string } | null }>; const result = await rpc.call(dependencies.supabase, name, args); if (result.error) return rpcFailure(result.error); if (!isUuid(result.data)) return failure(500, "server", "Không thể cập nhật quỹ đội. Vui lòng thử lại."); return Response.json({ ok: true, [idKey]: result.data }, { status }); }

export async function createFinanceEntry(request: Request, target: { slug: string }, supplied?: FundsActionDependencies) {
  try { const requestInput = await input(request); if (requestInput.response) return requestInput.response; const parsed = validateCreateFinanceEntryPayload(requestInput.value); if (!parsed.ok) return parsed.kind === "malformed" ? failure(400, "malformed", "Dữ liệu yêu cầu không hợp lệ.") : failure(422, "validation", "Vui lòng kiểm tra giao dịch.", parsed.fieldErrors); const { dependencies, context } = await authorize(target.slug, supplied); if (!context) return failure(403, "forbidden", "Bạn không có quyền quản lý quỹ đội."); return invoke(dependencies, "manage_finance_entry", { p_action: "create", p_team_id: context.team.id, p_entry_id: null, p_direction: parsed.value.direction, p_amount_vnd: parsed.value.amountVnd, p_category: parsed.value.category, p_occurred_on: parsed.value.occurredOn, p_description: parsed.value.description, p_void_reason: null, p_expected_updated_at: null }, "entryId", 201); } catch { return failure(500, "server", "Không thể cập nhật quỹ đội. Vui lòng thử lại."); }
}
export async function mutateFinanceEntry(request: Request, target: { slug: string }, supplied?: FundsActionDependencies) {
  try { const requestInput = await input(request); if (requestInput.response) return requestInput.response; const parsed = validateFinanceEntryMutationPayload(requestInput.value); if (!parsed.ok) return parsed.kind === "malformed" ? failure(400, "malformed", "Dữ liệu yêu cầu không hợp lệ.") : failure(422, "validation", "Vui lòng kiểm tra giao dịch.", parsed.fieldErrors); const { dependencies, context } = await authorize(target.slug, supplied); if (!context) return failure(403, "forbidden", "Bạn không có quyền quản lý quỹ đội."); return invoke(dependencies, "manage_finance_entry", { p_action: "void", p_team_id: context.team.id, p_entry_id: parsed.value.entryId, p_direction: null, p_amount_vnd: null, p_category: null, p_occurred_on: null, p_description: null, p_void_reason: parsed.value.reason, p_expected_updated_at: parsed.value.expectedUpdatedAt }, "entryId"); } catch { return failure(500, "server", "Không thể cập nhật quỹ đội. Vui lòng thử lại."); }
}
export async function mutateMemberDue(request: Request, target: { slug: string }, supplied?: FundsActionDependencies) {
  try { const requestInput = await input(request); if (requestInput.response) return requestInput.response; const parsed = validateMemberDuePayload(requestInput.value); if (!parsed.ok) return parsed.kind === "malformed" ? failure(400, "malformed", "Dữ liệu yêu cầu không hợp lệ.") : failure(422, "validation", "Vui lòng kiểm tra khoản phí.", parsed.fieldErrors); const { dependencies, context } = await authorize(target.slug, supplied); if (!context) return failure(403, "forbidden", "Bạn không có quyền quản lý quỹ đội."); const payload = parsed.value; return invoke(dependencies, "manage_member_due", { p_action: payload.action === "voidPayment" ? "void_payment" : payload.action, p_team_id: context.team.id, p_due_id: "dueId" in payload ? payload.dueId : null, p_user_id: "userId" in payload ? payload.userId : null, p_period_start: "periodStart" in payload ? payload.periodStart : null, p_amount_vnd: "amountVnd" in payload ? payload.amountVnd : null, p_due_date: "dueDate" in payload ? payload.dueDate : null, p_note: "note" in payload ? payload.note : "reason" in payload ? payload.reason : null, p_expected_updated_at: "expectedUpdatedAt" in payload ? payload.expectedUpdatedAt : null }, "dueId", payload.action === "create" ? 201 : 200); } catch { return failure(500, "server", "Không thể cập nhật quỹ đội. Vui lòng thử lại."); }
}
