import assert from "node:assert/strict";
import { resolve } from "node:path";
import test from "node:test";
import { Window } from "happy-dom";
import { build } from "vite";

import type { FundsResult } from "../lib/funds/model";
import type { PermissionCode } from "../lib/teams/permissions";

declare global { var __fundsRefreshes: number | undefined; }
const ENTRY_ID = "00000000-0000-4000-8000-000000000011"; const DUE_ID = "00000000-0000-4000-8000-000000000021"; const UPDATED_AT = "2026-10-01T08:00:00.000Z";
const RESULT: FundsResult = { ok: true, data: { periodStart: "2026-10-01", balanceVnd: 1_750_000, monthIncomeVnd: 500_000, monthIncomeCount: 1, monthExpenseVnd: 750_000, monthExpenseCount: 1, pendingDuesVnd: 500_000, pendingDuesCount: 1, paidDuesCount: 1, totalDuesCount: 2, dues: [{ id: DUE_ID, userId: "00000000-0000-4000-8000-000000000002", displayName: "Nguyễn An", periodStart: "2026-10-01", amountVnd: 500_000, dueDate: "2026-10-10", status: "pending", paidAt: null, financeEntryId: null, updatedAt: UPDATED_AT }, { id: "00000000-0000-4000-8000-000000000022", userId: "00000000-0000-4000-8000-000000000003", displayName: "Trần Bình", periodStart: "2026-10-01", amountVnd: 500_000, dueDate: "2026-10-10", status: "paid", paidAt: "2026-10-18T08:00:00.000Z", financeEntryId: "00000000-0000-4000-8000-000000000012", updatedAt: UPDATED_AT }], recentEntries: [{ id: ENTRY_ID, direction: "expense", amountVnd: 750_000, category: "equipment", occurredOn: "2026-10-24", description: "Mua bóng", createdAt: "2026-10-24T08:00:00.000Z", updatedAt: UPDATED_AT }] } };
let FundsView: (props: { team: { id: string; name: string; slug: string }; permissions: readonly PermissionCode[]; result: FundsResult }) => React.ReactNode; let act: (callback: () => void | Promise<void>) => Promise<void>; let createElement: typeof import("react").createElement; let createRoot: (container: Element) => { render(node: React.ReactNode): void; unmount(): void }; let browserWindow: Window;
const initialHandles = new Set(process._getActiveHandles());
test.before(async () => {
  browserWindow = new Window({ url: "https://pro7.example/teams/pro7-fc/funds" });
  for (const [key, value] of Object.entries({ window: browserWindow, document: browserWindow.document, navigator: browserWindow.navigator, HTMLElement: browserWindow.HTMLElement, HTMLInputElement: browserWindow.HTMLInputElement, HTMLSelectElement: browserWindow.HTMLSelectElement, HTMLTextAreaElement: browserWindow.HTMLTextAreaElement, Node: browserWindow.Node, Event: browserWindow.Event, FormData: browserWindow.FormData, IS_REACT_ACT_ENVIRONMENT: true })) Object.defineProperty(globalThis, key, { configurable: true, writable: true, value });
  const previousNodeEnvironment = process.env.NODE_ENV;
  process.env.NODE_ENV = "test";
  const result = await build({ configFile: false, mode: "test", plugins: [{ name: "funds-navigation", enforce: "pre", resolveId(id) { return id === "next/navigation" ? "\0funds-navigation" : null; }, load(id) { return id === "\0funds-navigation" ? "export function useRouter(){return {refresh(){globalThis.__fundsRefreshes=(globalThis.__fundsRefreshes??0)+1}}}" : null; } }], build: { lib: { entry: resolve("tests/funds-mounted-entry.ts"), formats: ["cjs"], fileName: "funds-mounted" }, write: false } });
  process.env.NODE_ENV = previousNodeEnvironment ?? "test";
  const code = (Array.isArray(result) ? result : [result]).flatMap((bundle) => bundle.output).find((output) => output.type === "chunk" && output.isEntry)?.code; assert.ok(code); const bundleModule = { exports: {} as Record<string, unknown> }; new Function("module", "exports", code)(bundleModule, bundleModule.exports); ({ FundsView, act, createElement, createRoot } = bundleModule.exports as never);
});
test.after(async () => { await browserWindow.happyDOM.abort(); browserWindow.close(); for (const handle of process._getActiveHandles()) if (!initialHandles.has(handle) && handle.constructor.name === "MessagePort") (handle as MessagePort).close(); });
async function mounted() { browserWindow.document.body.innerHTML = '<div id="root"></div>'; const container = browserWindow.document.getElementById("root"); assert.ok(container); const root = createRoot(container); globalThis.__fundsRefreshes = 0; await act(async () => root.render(createElement(FundsView, { team: { id: "team-1", name: "PRO7 FC", slug: "pro7-fc" }, permissions: ["finance.read", "finance.manage"], result: RESULT }))); return { container, root }; }
function input(control: HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement, value: string) { Object.getOwnPropertyDescriptor(Object.getPrototypeOf(control), "value")?.set?.call(control, value); control.dispatchEvent(new browserWindow.Event("input", { bubbles: true })); control.dispatchEvent(new browserWindow.Event("change", { bubbles: true })); }

test("expense dialog sends same-origin JSON without a client balance and refreshes after success", async () => {
  const calls: { url: string; init?: RequestInit }[] = []; globalThis.fetch = (async (request, init) => { calls.push({ url: String(request), init }); return Response.json({ ok: true, entryId: ENTRY_ID }, { status: 201 }); }) as typeof fetch;
  const view = await mounted(); const trigger = [...view.container.querySelectorAll("button")].find((button) => button.textContent?.includes("Thêm khoản chi")); assert.ok(trigger); await act(async () => trigger.click()); const form = view.container.querySelector<HTMLFormElement>('form[data-form="finance-entry"]'); assert.ok(form); input(form.elements.namedItem("amountVnd") as HTMLInputElement, "1200000"); input(form.elements.namedItem("category") as HTMLInputElement, "Thuê sân"); input(form.elements.namedItem("occurredOn") as HTMLInputElement, "2026-10-26"); input(form.elements.namedItem("description") as HTMLTextAreaElement, "Thuê sân Riverside"); await act(async () => { form.dispatchEvent(new browserWindow.Event("submit", { bubbles: true, cancelable: true })); await new Promise((resolvePromise) => setTimeout(resolvePromise, 0)); });
  assert.deepEqual(calls, [{ url: "/api/teams/pro7-fc/funds/entries", init: { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ direction: "expense", amountVnd: 1_200_000, category: "Thuê sân", occurredOn: "2026-10-26", description: "Thuê sân Riverside" }) } }]); assert.equal(globalThis.__fundsRefreshes, 1); assert.equal(view.container.querySelector('[role="dialog"]'), null); await act(async () => view.root.unmount());
});

test("payment and void actions preserve stale tokens, show loading, and refresh", async () => {
  const calls: { url: string; init?: RequestInit }[] = []; let resolveResponse: ((response: Response) => void) | undefined; globalThis.fetch = (async (request, init) => { calls.push({ url: String(request), init }); return new Promise<Response>((resolve) => { resolveResponse = resolve; }); }) as typeof fetch;
  const view = await mounted(); const pay = [...view.container.querySelectorAll("button")].find((button) => button.textContent?.trim() === "Đánh dấu đã đóng"); assert.ok(pay); await act(async () => { pay.click(); await Promise.resolve(); }); assert.equal(pay.disabled, true); assert.match(pay.textContent ?? "", /Đang lưu/u); assert.deepEqual(JSON.parse(String(calls[0]?.init?.body)), { action: "pay", dueId: DUE_ID, note: null, expectedUpdatedAt: UPDATED_AT }); await act(async () => { resolveResponse?.(Response.json({ ok: true })); await new Promise((resolvePromise) => setTimeout(resolvePromise, 0)); }); assert.equal(globalThis.__fundsRefreshes, 1); await act(async () => view.root.unmount());
});

test("field and stale errors remain visible without refreshing", async () => {
  globalThis.fetch = (async () => Response.json({ ok: false, code: "validation", message: "Kiểm tra dữ liệu.", fieldErrors: { amountVnd: "Số tiền không hợp lệ." } }, { status: 422 })) as typeof fetch;
  const view = await mounted(); const trigger = [...view.container.querySelectorAll("button")].find((button) => button.textContent?.includes("Thêm khoản chi")); assert.ok(trigger); await act(async () => trigger.click()); const form = view.container.querySelector<HTMLFormElement>('form[data-form="finance-entry"]'); assert.ok(form); input(form.elements.namedItem("amountVnd") as HTMLInputElement, "1"); input(form.elements.namedItem("category") as HTMLInputElement, "Phí"); input(form.elements.namedItem("occurredOn") as HTMLInputElement, "2026-10-26"); input(form.elements.namedItem("description") as HTMLTextAreaElement, "Chi"); await act(async () => { form.dispatchEvent(new browserWindow.Event("submit", { bubbles: true, cancelable: true })); await new Promise((resolvePromise) => setTimeout(resolvePromise, 0)); }); assert.match(view.container.textContent ?? "", /Số tiền không hợp lệ/u); assert.equal(globalThis.__fundsRefreshes, 0); await act(async () => view.root.unmount());
});
