import assert from "node:assert/strict";
import { resolve } from "node:path";
import test from "node:test";
import { Window } from "happy-dom";
import { build } from "vite";

import type { FundsResult } from "../lib/funds/model";
import type { TeamPaymentSettings } from "../lib/settings/model";
import type { PermissionCode } from "../lib/teams/permissions";

declare global { var __fundsRefreshes: number | undefined; }
const ENTRY_ID = "00000000-0000-4000-8000-000000000011"; const DUE_ID = "00000000-0000-4000-8000-000000000021"; const UPDATED_AT = "2026-10-01T08:00:00.000Z";
const RECENT = Array.from({ length: 6 }, (_, index) => ({ id: `00000000-0000-4000-8000-${(index + 11).toString().padStart(12, "0")}`, direction: index === 1 ? "income" as const : "expense" as const, amountVnd: 750_000 + index, category: "equipment", occurredOn: `2026-10-${String(24 - index).padStart(2, "0")}`, description: index === 0 ? "Mua bóng" : `Giao dịch ${index + 1}`, createdAt: `2026-10-${String(24 - index).padStart(2, "0")}T08:00:00.000Z`, updatedAt: UPDATED_AT }));
const RESULT: FundsResult = { ok: true, data: { periodStart: "2026-10-01", balanceVnd: 1_750_000, monthIncomeVnd: 500_000, monthIncomeCount: 1, monthExpenseVnd: 750_000, monthExpenseCount: 1, pendingDuesVnd: 500_000, pendingDuesCount: 1, paidDuesCount: 1, totalDuesCount: 2, dues: [{ id: DUE_ID, userId: "00000000-0000-4000-8000-000000000002", displayName: "Nguyễn An", periodStart: "2026-10-01", amountVnd: 500_000, dueDate: "2026-10-10", status: "pending", paidAt: null, financeEntryId: null, updatedAt: UPDATED_AT }, { id: "00000000-0000-4000-8000-000000000022", userId: "00000000-0000-4000-8000-000000000003", displayName: "Trần Bình", periodStart: "2026-10-01", amountVnd: 500_000, dueDate: "2026-10-10", status: "paid", paidAt: "2026-10-18T08:00:00.000Z", financeEntryId: "00000000-0000-4000-8000-000000000012", updatedAt: UPDATED_AT }], dueCandidates: [{ userId: "00000000-0000-4000-8000-000000000004", displayName: "Lê Cường" }], recentEntries: RECENT } };
let FundsView: (props: { team: { id: string; name: string; slug: string }; permissions: readonly PermissionCode[]; result: FundsResult; paymentSettings: TeamPaymentSettings | null; initialDialog?: "entry" }) => React.ReactNode; let act: (callback: () => void | Promise<void>) => Promise<void>; let createElement: typeof import("react").createElement; let createRoot: (container: Element) => { render(node: React.ReactNode): void; unmount(): void }; let browserWindow: Window;
const initialHandles = new Set(process._getActiveHandles());
test.before(async () => {
  browserWindow = new Window({ url: "https://pro7.example/teams/pro7-fc/funds" });
  for (const [key, value] of Object.entries({ window: browserWindow, document: browserWindow.document, navigator: browserWindow.navigator, HTMLElement: browserWindow.HTMLElement, HTMLInputElement: browserWindow.HTMLInputElement, HTMLSelectElement: browserWindow.HTMLSelectElement, HTMLTextAreaElement: browserWindow.HTMLTextAreaElement, Node: browserWindow.Node, Event: browserWindow.Event, FormData: browserWindow.FormData, IS_REACT_ACT_ENVIRONMENT: true })) Object.defineProperty(globalThis, key, { configurable: true, writable: true, value });
  const previousNodeEnvironment = process.env.NODE_ENV;
  process.env.NODE_ENV = "test";
  const result = await build({ configFile: false, mode: "test", plugins: [{ name: "funds-navigation", enforce: "pre", resolveId(id) { return id === "next/navigation" ? "\0funds-navigation" : null; }, load(id) { return id === "\0funds-navigation" ? "export function useRouter(){return {refresh(){globalThis.__fundsRefreshes=(globalThis.__fundsRefreshes??0)+1}}}" : null; } }], build: { lib: { entry: resolve("tests/funds-mounted-entry.ts"), formats: ["cjs"], fileName: "funds-mounted" }, write: false } });
  process.env.NODE_ENV = previousNodeEnvironment ?? "test";
  const code = (Array.isArray(result) ? result : [result]).flatMap((bundle) => bundle.output).find((output) => output.type === "chunk" && output.isEntry)?.code; assert.ok(code); const bundleModule = { exports: {} as Record<string, unknown> }; new Function("module", "exports", code)(bundleModule, bundleModule.exports); ({ FundsView, act, createElement, createRoot } = bundleModule.exports as never);
});
test.after(async () => { await browserWindow.happyDOM.abort(); browserWindow.close(); for (const handle of process._getActiveHandles()) if (!initialHandles.has(handle) && handle.constructor.name === "MessagePort") (handle as MessagePort).close(); });
const PAYMENT: TeamPaymentSettings = { bankCode: "VCB", accountNumber: "1234567890", accountHolder: "LE DUC", transferPrefix: "PRO7 QUY" };
async function mounted(initialDialog?: "entry", paymentSettings: TeamPaymentSettings | null = PAYMENT, result: FundsResult = RESULT) { browserWindow.document.body.innerHTML = '<div id="root"></div>'; const container = browserWindow.document.getElementById("root"); assert.ok(container); const root = createRoot(container); globalThis.__fundsRefreshes = 0; await act(async () => root.render(createElement(FundsView, { team: { id: "team-1", name: "PRO7 FC", slug: "pro7-fc" }, permissions: ["finance.read", "finance.manage"], result, paymentSettings, initialDialog }))); return { container, root }; }
async function input(control: HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement, value: string) { await act(async () => { Object.getOwnPropertyDescriptor(Object.getPrototypeOf(control), "value")?.set?.call(control, value); control.dispatchEvent(new browserWindow.Event("input", { bubbles: true })); control.dispatchEvent(new browserWindow.Event("change", { bubbles: true })); }); }

test("expense dialog sends same-origin JSON without a client balance and refreshes after success", async () => {
  const calls: { url: string; init?: RequestInit }[] = []; globalThis.fetch = (async (request, init) => { calls.push({ url: String(request), init }); return Response.json({ ok: true, entryId: ENTRY_ID }, { status: 201 }); }) as typeof fetch;
  const view = await mounted(); const trigger = [...view.container.querySelectorAll("button")].find((button) => button.textContent?.includes("Thêm khoản chi")); assert.ok(trigger); await act(async () => trigger.click()); const form = view.container.querySelector<HTMLFormElement>('form[data-form="finance-entry"]'); assert.ok(form); await input(form.elements.namedItem("amountVnd") as HTMLInputElement, "1200000"); await input(form.elements.namedItem("category") as HTMLInputElement, "Thuê sân"); await input(form.elements.namedItem("occurredOn") as HTMLInputElement, "2026-10-26"); await input(form.elements.namedItem("description") as HTMLTextAreaElement, "Thuê sân Riverside"); await act(async () => { form.dispatchEvent(new browserWindow.Event("submit", { bubbles: true, cancelable: true })); await new Promise((resolvePromise) => setTimeout(resolvePromise, 0)); });
  assert.deepEqual(calls, [{ url: "/api/teams/pro7-fc/funds/entries", init: { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ direction: "expense", amountVnd: 1_200_000, category: "Thuê sân", occurredOn: "2026-10-26", description: "Thuê sân Riverside" }) } }]); assert.equal(globalThis.__fundsRefreshes, 1); assert.equal(view.container.querySelector('[role="dialog"]'), null); await act(async () => view.root.unmount());
});

test("entry dialog supports authoritative income and restores focus after Escape", async () => {
  const calls: { body: unknown }[] = []; globalThis.fetch = (async (_request, init) => { calls.push({ body: JSON.parse(String(init?.body)) }); return Response.json({ ok: true, entryId: ENTRY_ID }, { status: 201 }); }) as typeof fetch;
  const view = await mounted(); const trigger = [...view.container.querySelectorAll("button")].find((button) => button.textContent?.includes("Thêm khoản chi")); assert.ok(trigger); trigger.focus(); await act(async () => trigger.click()); const form = view.container.querySelector<HTMLFormElement>('form[data-form="finance-entry"]'); assert.ok(form); const direction = form.elements.namedItem("direction") as HTMLSelectElement; assert.equal(document.activeElement, direction); await input(direction, "income"); await input(form.elements.namedItem("amountVnd") as HTMLInputElement, "900000"); await input(form.elements.namedItem("category") as HTMLInputElement, "Tài trợ"); await input(form.elements.namedItem("occurredOn") as HTMLInputElement, "2026-10-27"); await input(form.elements.namedItem("description") as HTMLTextAreaElement, "Nhà tài trợ tháng 10"); await act(async () => { form.dispatchEvent(new browserWindow.Event("submit", { bubbles: true, cancelable: true })); await new Promise((resolvePromise) => setTimeout(resolvePromise, 0)); }); assert.deepEqual(calls[0]?.body, { direction: "income", amountVnd: 900000, category: "Tài trợ", occurredOn: "2026-10-27", description: "Nhà tài trợ tháng 10" });
  await act(async () => trigger.click()); await act(async () => document.dispatchEvent(new browserWindow.KeyboardEvent("keydown", { key: "Escape", bubbles: true }) as unknown as Event)); assert.equal(view.container.querySelector('[role="dialog"]'), null); assert.equal(document.activeElement, trigger); await act(async () => view.root.unmount());
});

test("payment and void actions preserve stale tokens, show loading, and refresh", async () => {
  const calls: { url: string; init?: RequestInit }[] = []; let resolveResponse: ((response: Response) => void) | undefined; globalThis.fetch = (async (request, init) => { calls.push({ url: String(request), init }); return new Promise<Response>((resolve) => { resolveResponse = resolve; }); }) as typeof fetch;
  const view = await mounted(); const pay = [...view.container.querySelectorAll("button")].find((button) => button.textContent?.trim() === "Đánh dấu đã đóng"); assert.ok(pay); await act(async () => { pay.click(); await Promise.resolve(); }); assert.equal(pay.disabled, true); assert.match(pay.textContent ?? "", /Đang lưu/u); assert.deepEqual(JSON.parse(String(calls[0]?.init?.body)), { action: "pay", dueId: DUE_ID, note: null, expectedUpdatedAt: UPDATED_AT }); await act(async () => { resolveResponse?.(Response.json({ ok: true })); await new Promise((resolvePromise) => setTimeout(resolvePromise, 0)); }); assert.equal(globalThis.__fundsRefreshes, 1); await act(async () => view.root.unmount());
});

test("Admin can create a due and waive a pending due with stable errors then refresh", async () => {
  const calls: unknown[] = []; let waiveAttempts = 0; globalThis.fetch = (async (_request, init) => { const payload = JSON.parse(String(init?.body)); calls.push(payload); if (payload.action === "waive" && waiveAttempts++ === 0) return Response.json({ ok: false, code: "stale", message: "Dữ liệu quỹ đã thay đổi. Vui lòng tải lại." }, { status: 409 }); return Response.json({ ok: true, dueId: DUE_ID }, { status: payload.action === "create" ? 201 : 200 }); }) as typeof fetch;
  const view = await mounted(); const payment = [...view.container.querySelectorAll("button")].find((button) => button.textContent?.includes("Ghi nhận đóng quỹ")); assert.ok(payment); await act(async () => payment.click()); const form = view.container.querySelector<HTMLFormElement>('form[data-form="member-due"]'); assert.ok(form); await input(form.elements.namedItem("operation") as HTMLSelectElement, "create"); await input(form.elements.namedItem("userId") as HTMLSelectElement, "00000000-0000-4000-8000-000000000004"); await input(form.elements.namedItem("amountVnd") as HTMLInputElement, "500000"); await input(form.elements.namedItem("dueDate") as HTMLInputElement, "2026-10-10"); await act(async () => { form.dispatchEvent(new browserWindow.Event("submit", { bubbles: true, cancelable: true })); await new Promise((resolvePromise) => setTimeout(resolvePromise, 0)); }); assert.deepEqual(calls[0], { action: "create", userId: "00000000-0000-4000-8000-000000000004", periodStart: "2026-10-01", amountVnd: 500000, dueDate: "2026-10-10" });
  const waive = [...view.container.querySelectorAll("button")].find((button) => button.textContent?.trim() === "Miễn phí"); assert.ok(waive); await act(async () => { waive.click(); await new Promise((resolvePromise) => setTimeout(resolvePromise, 0)); }); assert.match(view.container.textContent ?? "", /Dữ liệu quỹ đã thay đổi/u); assert.equal(globalThis.__fundsRefreshes, 1); await act(async () => { waive.click(); await new Promise((resolvePromise) => setTimeout(resolvePromise, 0)); }); assert.deepEqual(calls.at(-1), { action: "waive", dueId: DUE_ID, expectedUpdatedAt: UPDATED_AT }); assert.equal(globalThis.__fundsRefreshes, 2); await act(async () => view.root.unmount());
});

test("reminder copies bounded live summary and transactions expand then collapse", async () => {
  const writes: string[] = []; Object.defineProperty(browserWindow.navigator, "clipboard", { configurable: true, value: { writeText: async (value: string) => { writes.push(value); } } });
  const view = await mounted(); assert.doesNotMatch(view.container.textContent ?? "", /Giao dịch 6/u); const expand = [...view.container.querySelectorAll("button")].find((button) => button.textContent?.includes("Xem tất cả")); assert.ok(expand); await act(async () => expand.click()); assert.match(view.container.textContent ?? "", /Giao dịch 6/u); assert.match(expand.textContent ?? "", /Thu gọn/u); await act(async () => expand.click()); assert.doesNotMatch(view.container.textContent ?? "", /Giao dịch 6/u);
  const remind = [...view.container.querySelectorAll("button")].find((button) => button.textContent?.includes("Nhắc 1 thành viên chưa đóng")); assert.ok(remind); await act(async () => { remind.click(); await Promise.resolve(); }); assert.equal(writes.length, 1); assert.match(writes[0] ?? "", /Nguyễn An[\s\S]*500\.000[^\n]*₫/u); assert.ok((writes[0]?.length ?? 0) <= 1000); assert.match(view.container.textContent ?? "", /Đã sao chép lời nhắc/u); await act(async () => view.root.unmount());
});

test("reminder and dues forms expose bounded error and accessible field states", async () => {
  Object.defineProperty(browserWindow.navigator, "clipboard", { configurable: true, value: { writeText: async () => { throw new Error("denied"); } } });
  globalThis.fetch = (async (_request, init) => { const payload = JSON.parse(String(init?.body)); return payload.action === "pay" ? Response.json({ ok: false, code: "validation", message: "Kiểm tra thanh toán.", fieldErrors: { dueId: "Khoản phí không hợp lệ.", note: "Ghi chú không hợp lệ." } }, { status: 422 }) : Response.json({ ok: false, code: "validation", message: "Kiểm tra khoản phí.", fieldErrors: { userId: "Thành viên không hợp lệ.", periodStart: "Kỳ phí không hợp lệ.", amountVnd: "Số tiền không hợp lệ.", dueDate: "Hạn đóng không hợp lệ." } }, { status: 422 }); }) as typeof fetch;
  const view = await mounted(); const remind = [...view.container.querySelectorAll("button")].find((button) => button.textContent?.includes("Nhắc 1 thành viên chưa đóng")); assert.ok(remind); await act(async () => { remind.click(); await Promise.resolve(); }); assert.match(view.container.textContent ?? "", /Không thể sao chép lời nhắc/u);
  const payment = [...view.container.querySelectorAll("button")].find((button) => button.textContent?.includes("Ghi nhận đóng quỹ")); assert.ok(payment); payment.focus(); await act(async () => payment.click()); const form = view.container.querySelector<HTMLFormElement>('form[data-form="member-due"]'); assert.ok(form); const operation = form.elements.namedItem("operation") as HTMLSelectElement; assert.equal(document.activeElement, operation); await input(form.elements.namedItem("dueId") as HTMLSelectElement, DUE_ID); await input(form.elements.namedItem("note") as HTMLTextAreaElement, "Ghi chú"); await act(async () => { form.dispatchEvent(new browserWindow.Event("submit", { bubbles: true, cancelable: true })); await new Promise((resolvePromise) => setTimeout(resolvePromise, 0)); }); for (const name of ["dueId", "note"]) { const control = form.elements.namedItem(name) as HTMLElement; assert.equal(control.getAttribute("aria-invalid"), "true"); assert.ok(control.getAttribute("aria-describedby")); }
  await input(operation, "create"); await input(form.elements.namedItem("userId") as HTMLSelectElement, "00000000-0000-4000-8000-000000000004"); await input(form.elements.namedItem("amountVnd") as HTMLInputElement, "500000"); await input(form.elements.namedItem("dueDate") as HTMLInputElement, "2026-10-10"); await act(async () => { form.dispatchEvent(new browserWindow.Event("submit", { bubbles: true, cancelable: true })); await new Promise((resolvePromise) => setTimeout(resolvePromise, 0)); }); for (const name of ["userId", "periodStart", "amountVnd", "dueDate"]) { const control = form.elements.namedItem(name) as HTMLElement; assert.equal(control.getAttribute("aria-invalid"), "true"); const describedBy = control.getAttribute("aria-describedby"); assert.ok(describedBy); assert.equal(view.container.querySelectorAll(`#${describedBy}`).length, 1); } await act(async () => view.root.unmount());
});

test("field errors bind unique accessible descriptions without refreshing", async () => {
  globalThis.fetch = (async () => Response.json({ ok: false, code: "validation", message: "Kiểm tra dữ liệu.", fieldErrors: { amountVnd: "Số tiền không hợp lệ.", category: "Danh mục không hợp lệ.", occurredOn: "Ngày không hợp lệ.", description: "Nội dung không hợp lệ." } }, { status: 422 })) as typeof fetch;
  const view = await mounted(); const trigger = [...view.container.querySelectorAll("button")].find((button) => button.textContent?.includes("Thêm khoản chi")); assert.ok(trigger); await act(async () => trigger.click()); const form = view.container.querySelector<HTMLFormElement>('form[data-form="finance-entry"]'); assert.ok(form); await input(form.elements.namedItem("amountVnd") as HTMLInputElement, "1"); await input(form.elements.namedItem("category") as HTMLInputElement, "Phí"); await input(form.elements.namedItem("occurredOn") as HTMLInputElement, "2026-10-26"); await input(form.elements.namedItem("description") as HTMLTextAreaElement, "Chi"); await act(async () => { form.dispatchEvent(new browserWindow.Event("submit", { bubbles: true, cancelable: true })); await new Promise((resolvePromise) => setTimeout(resolvePromise, 0)); }); for (const name of ["amountVnd", "category", "occurredOn", "description"]) { const control = form.elements.namedItem(name) as HTMLElement; assert.equal(control.getAttribute("aria-invalid"), "true"); const describedBy = control.getAttribute("aria-describedby"); assert.ok(describedBy); assert.equal(view.container.querySelectorAll(`#${describedBy}`).length, 1); } assert.equal(globalThis.__fundsRefreshes, 0); await act(async () => view.root.unmount());
});

test("VietQR selects a real pending due, derives amount and content, then copies without mutation", async () => {
  const writes: string[] = []; const fetchCalls: unknown[] = [];
  Object.defineProperty(browserWindow.navigator, "clipboard", { configurable: true, value: { writeText: async (value: string) => { writes.push(value); } } });
  globalThis.fetch = (async (...args) => { fetchCalls.push(args); return Response.json({ ok: false }, { status: 500 }); }) as typeof fetch;
  const view = await mounted(); const trigger = [...view.container.querySelectorAll("button")].find((button) => button.textContent?.includes("VietQR")); assert.ok(trigger); trigger.focus(); await act(async () => trigger.click());
  const dialog = view.container.querySelector<HTMLElement>('[role="dialog"]'); assert.ok(dialog); const select = dialog.querySelector<HTMLSelectElement>('select[name="dueId"]'); assert.ok(select); assert.equal(document.activeElement, select); assert.equal(select.value, DUE_ID);
  const image = dialog.querySelector<HTMLImageElement>('img[alt="Mã VietQR nộp quỹ"]'); assert.ok(image); const url = new URL(image.src); assert.match(url.pathname, /VCB-1234567890-compact2\.png$/u); assert.equal(url.searchParams.get("amount"), "500000"); assert.equal(url.searchParams.get("addInfo"), "PRO7 QUY NGUYEN AN"); assert.equal(url.searchParams.get("accountName"), "LE DUC");
  const copy = [...dialog.querySelectorAll("button")].find((button) => button.textContent?.includes("Sao chép số tài khoản")); assert.ok(copy); await act(async () => { copy.click(); await Promise.resolve(); }); assert.deepEqual(writes, ["1234567890"]); assert.match(dialog.textContent ?? "", /Đã sao chép số tài khoản/u); assert.deepEqual(fetchCalls, []);
  await act(async () => document.dispatchEvent(new browserWindow.KeyboardEvent("keydown", { key: "Escape", bubbles: true }) as unknown as Event)); assert.equal(view.container.querySelector('[role="dialog"]'), null); assert.equal(document.activeElement, trigger); await act(async () => view.root.unmount());
});

test("VietQR renders honest missing-config and no-pending states", async () => {
  const missing = await mounted(undefined, null); const trigger = [...missing.container.querySelectorAll("button")].find((button) => button.textContent?.includes("VietQR")); assert.ok(trigger); await act(async () => trigger.click()); assert.match(missing.container.textContent ?? "", /Chưa cấu hình tài khoản nhận quỹ/u); assert.match(missing.container.querySelector('a[href="/teams/pro7-fc/admin/settings#payments"]')?.textContent ?? "", /Mở Admin Settings/u); assert.equal(missing.container.querySelector('.vietqr-code-img img'), null); await act(async () => missing.root.unmount());

  const noPendingResult: FundsResult = { ok: true, data: { ...RESULT.data, pendingDuesVnd: 0, pendingDuesCount: 0, dues: RESULT.data.dues.map((due) => ({ ...due, status: "paid" as const, paidAt: UPDATED_AT })) } };
  const noPending = await mounted(undefined, PAYMENT, noPendingResult); const noPendingTrigger = [...noPending.container.querySelectorAll("button")].find((button) => button.textContent?.includes("VietQR")); assert.ok(noPendingTrigger); await act(async () => noPendingTrigger.click()); assert.match(noPending.container.textContent ?? "", /Chưa có khoản phí đang chờ để tạo VietQR/u); assert.equal(noPending.container.querySelector('.vietqr-code-img img'), null); await act(async () => noPending.root.unmount());
});
