"use client";
/* eslint-disable @next/next/no-img-element -- VietQR is a dynamic external banking QR image and must not be proxied or cached. */

import { CircleDollarSign, Clock3, Coins, CreditCard, HandCoins, MapPin, MessageCircle, QrCode, Trophy, WalletCards, X } from "lucide-react";
import { useRouter } from "next/navigation";
import { useEffect, useRef, useState, type FormEvent, type RefObject } from "react";

import type { FinanceEntry, FundsResult, MemberDue } from "../../../../lib/funds/model";
import { buildVietQrUrl } from "../../../../lib/funds/vietqr";
import { formatVietnamDate } from "../../../../lib/matches/date-time";
import type { TeamPaymentSettings } from "../../../../lib/settings/model";
import type { TeamAccessContext } from "../../../../lib/teams/context";
import { hasPermission, type PermissionCode } from "../../../../lib/teams/permissions";

type ApiError = Readonly<{ message?: string; fieldErrors?: Readonly<Record<string, string>> }>;
type Dialog = { kind: "entry" } | { kind: "payment" } | { kind: "voidEntry"; entry: FinanceEntry } | { kind: "voidPayment"; due: MemberDue };

function formatVnd(value: number) { return `${new Intl.NumberFormat("vi-VN", { maximumFractionDigits: 0 }).format(value)}₫`; }
function formatDate(value: string) { return formatVietnamDate(value); }
function initials(value: string) { return value.trim().split(/\s+/u).slice(-2).map((part) => part[0]?.toLocaleUpperCase("vi-VN")).join("") || "TV"; }
function monthName(value: string) { return `THÁNG ${Number(value.slice(5, 7))}`; }
function responseError(value: unknown, fallback: string) { const error = typeof value === "object" && value !== null ? value as ApiError : {}; return { message: typeof error.message === "string" ? error.message : fallback, fieldErrors: error.fieldErrors ?? {} }; }
function errorAttributes(errors: Readonly<Record<string, string>>, field: string, prefix: string) { const invalid = Boolean(errors[field]); return { "aria-invalid": invalid, "aria-describedby": invalid ? `${prefix}-${field}-error` : undefined } as const; }
function FieldError({ errors, field, prefix }: { errors: Readonly<Record<string, string>>; field: string; prefix: string }) { return errors[field] ? <small id={`${prefix}-${field}-error`} className="fund-field-error">{errors[field]}</small> : null; }

function useDialogBoundary(close: () => void) {
  const dialogRef = useRef<HTMLElement>(null); const firstRef = useRef<HTMLElement>(null);
  useEffect(() => {
    const previous = document.activeElement instanceof HTMLElement ? document.activeElement : null; firstRef.current?.focus();
    function keydown(event: KeyboardEvent) {
      if (event.key === "Escape") { event.preventDefault(); close(); return; }
      if (event.key !== "Tab" || !dialogRef.current) return;
      const focusable = [...dialogRef.current.querySelectorAll<HTMLElement>('button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled])')].filter((element) => element.tabIndex >= 0); const first = focusable[0]; const last = focusable.at(-1);
      if (!first || !last) { event.preventDefault(); return; }
      if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); }
    }
    document.addEventListener("keydown", keydown); return () => { document.removeEventListener("keydown", keydown); previous?.focus(); };
  }, [close]);
  return { dialogRef, firstRef };
}

function EntryDialog({ slug, close }: { slug: string; close: () => void }) {
  const router = useRouter(); const [pending, setPending] = useState(false); const [message, setMessage] = useState(""); const [errors, setErrors] = useState<Readonly<Record<string, string>>>({}); const { dialogRef, firstRef } = useDialogBoundary(close);
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setPending(true); setMessage(""); setErrors({}); const form = new FormData(event.currentTarget); const payload = { direction: String(form.get("direction") ?? ""), amountVnd: Number(form.get("amountVnd")), category: String(form.get("category") ?? ""), occurredOn: String(form.get("occurredOn") ?? ""), description: String(form.get("description") ?? "") };
    try { const response = await fetch(`/api/teams/${encodeURIComponent(slug)}/funds/entries`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); const body: unknown = await response.json().catch(() => null); if (!response.ok) { const error = responseError(body, "Không thể lưu giao dịch."); setMessage(error.message); setErrors(error.fieldErrors); setPending(false); return; } router.refresh(); close(); } catch { setMessage("Không thể lưu giao dịch."); setPending(false); }
  }
  return <div className="modal-layer"><section ref={dialogRef} className="modal fund-modal" role="dialog" aria-modal="true" aria-labelledby="entry-dialog-title"><div className="modal-head"><div><span>QUỸ ĐỘI</span><h2 id="entry-dialog-title">Thêm khoản chi</h2><p>Ghi nhận khoản thu hoặc chi của đội.</p></div><button type="button" onClick={close} aria-label="Đóng"><X /></button></div><form data-form="finance-entry" onSubmit={(event) => void submit(event)}>
    <label>Loại giao dịch<select ref={firstRef as RefObject<HTMLSelectElement>} name="direction" defaultValue="expense" {...errorAttributes(errors, "direction", "entry")}><option value="expense">Khoản chi</option><option value="income">Khoản thu</option></select></label><FieldError errors={errors} field="direction" prefix="entry" />
    <label>Số tiền<input name="amountVnd" type="number" min="1" step="1" required {...errorAttributes(errors, "amountVnd", "entry")} /></label><FieldError errors={errors} field="amountVnd" prefix="entry" />
    <label>Danh mục<input name="category" maxLength={80} required {...errorAttributes(errors, "category", "entry")} /></label><FieldError errors={errors} field="category" prefix="entry" />
    <label>Ngày giao dịch<input name="occurredOn" type="date" required {...errorAttributes(errors, "occurredOn", "entry")} /></label><FieldError errors={errors} field="occurredOn" prefix="entry" />
    <label>Nội dung<textarea name="description" maxLength={500} required {...errorAttributes(errors, "description", "entry")} /></label><FieldError errors={errors} field="description" prefix="entry" />
    {message && <p className="fund-message error" role="alert">{message}</p>}<div className="modal-actions"><button className="soft-button" type="button" onClick={close}>Hủy</button><button className="primary-button" type="submit" disabled={pending}>{pending ? "Đang lưu…" : "Lưu giao dịch"}</button></div>
  </form></section></div>;
}

function PaymentDialog({ slug, data, close }: { slug: string; data: Extract<FundsResult, { ok: true }>["data"]; close: () => void }) {
  const router = useRouter(); const pendingDues = data.dues.filter((due) => due.status === "pending"); const [operation, setOperation] = useState<"pay" | "create">(pendingDues.length > 0 ? "pay" : "create"); const [pending, setPending] = useState(false); const [message, setMessage] = useState(""); const [errors, setErrors] = useState<Readonly<Record<string, string>>>({}); const { dialogRef, firstRef } = useDialogBoundary(close);
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const form = new FormData(event.currentTarget); let payload: Record<string, unknown>;
    if (operation === "pay") { const due = pendingDues.find(({ id }) => id === form.get("dueId")); if (!due) { setErrors({ dueId: "Chọn thành viên chưa đóng phí." }); return; } payload = { action: "pay", dueId: due.id, note: String(form.get("note") ?? "").trim() || null, expectedUpdatedAt: due.updatedAt }; }
    else payload = { action: "create", userId: String(form.get("userId") ?? ""), periodStart: data.periodStart, amountVnd: Number(form.get("amountVnd")), dueDate: String(form.get("dueDate") ?? "") };
    setPending(true); setMessage(""); setErrors({});
    try { const response = await fetch(`/api/teams/${encodeURIComponent(slug)}/funds/dues`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); const body: unknown = await response.json().catch(() => null); if (!response.ok) { const error = responseError(body, "Không thể cập nhật phí thành viên."); setMessage(error.message); setErrors(error.fieldErrors); setPending(false); return; } router.refresh(); close(); } catch { setMessage("Không thể cập nhật phí thành viên."); setPending(false); }
  }
  return <div className="modal-layer"><section ref={dialogRef} className="modal fund-modal" role="dialog" aria-modal="true" aria-labelledby="payment-dialog-title"><div className="modal-head"><div><span>QUỸ ĐỘI</span><h2 id="payment-dialog-title">Ghi nhận đóng quỹ</h2><p>Tạo phí hoặc cập nhật một khoản đang chờ.</p></div><button type="button" onClick={close} aria-label="Đóng"><X /></button></div><form data-form="member-due" onSubmit={(event) => void submit(event)}>
    <label>Thao tác<select ref={firstRef as RefObject<HTMLSelectElement>} name="operation" value={operation} onChange={(event) => { setOperation(event.target.value as "pay" | "create"); setMessage(""); setErrors({}); }}><option value="pay" disabled={pendingDues.length === 0}>Ghi nhận thanh toán</option><option value="create" disabled={data.dueCandidates.length === 0}>Tạo phí thành viên</option></select></label>
    {operation === "pay" ? <><label>Thành viên<select name="dueId" required defaultValue="" {...errorAttributes(errors, "dueId", "due-pay")}><option value="" disabled>Chọn thành viên</option>{pendingDues.map((due) => <option key={due.id} value={due.id}>{due.displayName} — {formatVnd(due.amountVnd)}</option>)}</select></label><FieldError errors={errors} field="dueId" prefix="due-pay" /><label>Ghi chú<textarea name="note" maxLength={300} {...errorAttributes(errors, "note", "due-pay")} /></label><FieldError errors={errors} field="note" prefix="due-pay" /></> : <><label>Thành viên<select name="userId" required defaultValue="" {...errorAttributes(errors, "userId", "due-create")}><option value="" disabled>Chọn thành viên</option>{data.dueCandidates.map((candidate) => <option key={candidate.userId} value={candidate.userId}>{candidate.displayName}</option>)}</select></label><FieldError errors={errors} field="userId" prefix="due-create" /><label>Kỳ phí<input name="periodStart" value={data.periodStart} readOnly {...errorAttributes(errors, "periodStart", "due-create")} /></label><FieldError errors={errors} field="periodStart" prefix="due-create" /><label>Số tiền<input name="amountVnd" type="number" min="1" step="1" required {...errorAttributes(errors, "amountVnd", "due-create")} /></label><FieldError errors={errors} field="amountVnd" prefix="due-create" /><label>Hạn đóng<input name="dueDate" type="date" required {...errorAttributes(errors, "dueDate", "due-create")} /></label><FieldError errors={errors} field="dueDate" prefix="due-create" /></>}
    {message && <p className="fund-message error" role="alert">{message}</p>}<div className="modal-actions"><button className="soft-button" type="button" onClick={close}>Hủy</button><button className="primary-button" type="submit" disabled={pending}>{pending ? "Đang lưu…" : operation === "pay" ? "Xác nhận thanh toán" : "Tạo khoản phí"}</button></div>
  </form></section></div>;
}

function VoidDialog({ slug, target, close }: { slug: string; target: Extract<Dialog, { kind: "voidEntry" | "voidPayment" }>; close: () => void }) {
  const router = useRouter(); const [pending, setPending] = useState(false); const [message, setMessage] = useState(""); const [errors, setErrors] = useState<Readonly<Record<string, string>>>({}); const { dialogRef, firstRef } = useDialogBoundary(close);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const reason = String(new FormData(event.currentTarget).get("reason") ?? ""); const isDue = target.kind === "voidPayment"; const payload = isDue ? { action: "voidPayment", dueId: target.due.id, reason, expectedUpdatedAt: target.due.updatedAt } : { action: "void", entryId: target.entry.id, reason, expectedUpdatedAt: target.entry.updatedAt }; setPending(true); setMessage(""); setErrors({}); try { const response = await fetch(`/api/teams/${encodeURIComponent(slug)}/funds/${isDue ? "dues" : "entries"}`, { method: isDue ? "POST" : "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); const body: unknown = await response.json().catch(() => null); if (!response.ok) { const error = responseError(body, "Không thể hủy giao dịch."); setMessage(error.message); setErrors(error.fieldErrors); setPending(false); return; } router.refresh(); close(); } catch { setMessage("Không thể hủy giao dịch."); setPending(false); } }
  return <div className="modal-layer"><section ref={dialogRef} className="modal fund-modal" role="dialog" aria-modal="true" aria-labelledby="void-dialog-title"><div className="modal-head"><div><span>ĐIỀU CHỈNH</span><h2 id="void-dialog-title">Hủy giao dịch</h2><p>{target.kind === "voidPayment" ? `Hoàn tác thanh toán của ${target.due.displayName}.` : target.entry.description}</p></div><button type="button" onClick={close} aria-label="Đóng"><X /></button></div><form onSubmit={(event) => void submit(event)}><label>Lý do<textarea ref={firstRef as RefObject<HTMLTextAreaElement>} name="reason" maxLength={300} required {...errorAttributes(errors, "reason", "void")} /></label><FieldError errors={errors} field="reason" prefix="void" />{message && <p className="fund-message error" role="alert">{message}</p>}<div className="modal-actions"><button className="soft-button" type="button" onClick={close}>Hủy</button><button className="fund-danger-button" type="submit" disabled={pending}>{pending ? "Đang lưu…" : "Xác nhận hủy"}</button></div></form></section></div>;
}

function DueRow({ slug, due, canManage, onVoid }: { slug: string; due: MemberDue; canManage: boolean; onVoid: () => void }) {
  const router = useRouter(); const [pendingAction, setPendingAction] = useState<"pay" | "waive" | null>(null); const [message, setMessage] = useState("");
  async function mutate(action: "pay" | "waive") { setPendingAction(action); setMessage(""); const payload = action === "pay" ? { action, dueId: due.id, note: null, expectedUpdatedAt: due.updatedAt } : { action, dueId: due.id, expectedUpdatedAt: due.updatedAt }; try { const response = await fetch(`/api/teams/${encodeURIComponent(slug)}/funds/dues`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); const body: unknown = await response.json().catch(() => null); if (!response.ok) { setMessage(responseError(body, "Không thể cập nhật phí thành viên.").message); setPendingAction(null); return; } setPendingAction(null); router.refresh(); } catch { setMessage("Không thể cập nhật phí thành viên."); setPendingAction(null); } }
  const paid = due.status === "paid";
  return <div className={`due-row ${due.status === "pending" ? "pending" : ""}`}><div className="initial-avatar">{initials(due.displayName)}</div><div><b>{due.displayName}</b><span>Hạn {formatDate(due.dueDate)}</span>{message && <small className="fund-row-error" role="alert">{message}</small>}</div><i className={paid ? "paid" : due.status === "pending" ? "unpaid" : "waived"}>{paid ? "Đã đóng" : due.status === "pending" ? "Chưa đóng" : "Đã miễn"}</i><strong>{formatVnd(due.amountVnd)}</strong>{canManage && due.status === "pending" && <div className="fund-row-actions"><button className="fund-row-action" disabled={pendingAction !== null} onClick={() => void mutate("pay")}>{pendingAction === "pay" ? "Đang lưu…" : "Đánh dấu đã đóng"}</button><button className="fund-row-action danger" disabled={pendingAction !== null} onClick={() => void mutate("waive")}>{pendingAction === "waive" ? "Đang lưu…" : "Miễn phí"}</button></div>}{canManage && paid && <button className="fund-row-action danger" onClick={onVoid}>Hủy thanh toán</button>}</div>;
}

function ReminderControl({ periodStart, dues }: { periodStart: string; dues: readonly MemberDue[] }) {
  const [state, setState] = useState({ pending: false, message: "", error: false });
  async function copy() { setState({ pending: true, message: "", error: false }); const summary = [`Nhắc đóng phí ${monthName(periodStart).toLocaleLowerCase("vi-VN")}:`, ...dues.map((due) => `${due.displayName}: ${formatVnd(due.amountVnd)} (hạn ${formatDate(due.dueDate)})`)].join("\n").slice(0, 1000); try { if (!navigator.clipboard?.writeText) throw new Error("Clipboard unavailable"); await navigator.clipboard.writeText(summary); setState({ pending: false, message: "Đã sao chép lời nhắc.", error: false }); } catch { setState({ pending: false, message: "Không thể sao chép lời nhắc.", error: true }); } }
  return <><button className="soft-button full-button" type="button" disabled={state.pending} onClick={() => void copy()}><MessageCircle size={16} />{state.pending ? "Đang sao chép…" : `Nhắc ${dues.length} thành viên chưa đóng`}</button>{state.message && <p className={`fund-control-status ${state.error ? "error" : "success"}`} role="status">{state.message}</p>}</>;
}

function VietQrDialog({ slug, paymentSettings, dues, close }: { slug: string; paymentSettings: TeamPaymentSettings | null; dues: readonly MemberDue[]; close: () => void }) {
  const [selectedDueId, setSelectedDueId] = useState(dues[0]?.id ?? "");
  const [copyState, setCopyState] = useState<{ message: string; error: boolean }>({ message: "", error: false });
  const { dialogRef, firstRef } = useDialogBoundary(close);
  const selectedDue = dues.find((due) => due.id === selectedDueId) ?? null;
  const qr = paymentSettings && selectedDue ? buildVietQrUrl(paymentSettings, selectedDue) : null;
  async function copyAccount() {
    if (!paymentSettings) return;
    try { if (!navigator.clipboard?.writeText) throw new Error("Clipboard unavailable"); await navigator.clipboard.writeText(paymentSettings.accountNumber); setCopyState({ message: "Đã sao chép số tài khoản.", error: false }); }
    catch { setCopyState({ message: "Không thể sao chép số tài khoản.", error: true }); }
  }
  return <div className="vietqr-popover"><section ref={dialogRef} className="vietqr-content" role="dialog" aria-modal="true" aria-labelledby="vietqr-title"><header className="vietqr-head"><div><span>QUỸ ĐỘI</span><h2 id="vietqr-title">VietQR nộp quỹ đội</h2></div><button ref={!paymentSettings || dues.length === 0 ? firstRef as RefObject<HTMLButtonElement> : undefined} type="button" onClick={close} aria-label="Đóng"><X size={20} /></button></header>
    {!paymentSettings ? <div className="vietqr-empty"><LandmarkFallback /><h3>Chưa cấu hình tài khoản nhận quỹ</h3><p>Admin cần bổ sung tài khoản ngân hàng trước khi tạo mã VietQR.</p><a className="primary-button" href={`/teams/${encodeURIComponent(slug)}/admin/settings#payments`}>Mở Admin Settings</a></div> : dues.length === 0 ? <div className="vietqr-empty"><QrCode /><h3>Chưa có khoản phí đang chờ để tạo VietQR</h3><p>Hãy tạo khoản phí thành viên trước. Mã QR không sử dụng số tiền ước tính.</p></div> : <><p className="vietqr-intro">Chọn đúng khoản phí đang chờ. Số tiền và nội dung chuyển khoản được tạo từ dữ liệu quỹ hiện tại.</p><label className="vietqr-due-select">Khoản phí<select ref={firstRef as RefObject<HTMLSelectElement>} name="dueId" value={selectedDueId} onChange={(event) => { setSelectedDueId(event.target.value); setCopyState({ message: "", error: false }); }}>{dues.map((due) => <option key={due.id} value={due.id}>{due.displayName} — {formatVnd(due.amountVnd)}</option>)}</select></label>{qr && selectedDue && <><div className="vietqr-code-img"><img src={qr.url} alt="Mã VietQR nộp quỹ" /></div><dl className="vietqr-account"><div><dt>Mã ngân hàng</dt><dd>{paymentSettings.bankCode}</dd></div><div><dt>Số tài khoản</dt><dd><code>{paymentSettings.accountNumber}</code></dd></div><div><dt>Chủ tài khoản</dt><dd>{paymentSettings.accountHolder}</dd></div><div><dt>Số tiền</dt><dd>{formatVnd(selectedDue.amountVnd)}</dd></div><div><dt>Nội dung</dt><dd><code>{qr.description}</code></dd></div></dl><button type="button" className="primary-button vietqr-copy" onClick={() => void copyAccount()}>Sao chép số tài khoản</button>{copyState.message && <p className={`vietqr-status ${copyState.error ? "error" : "success"}`} role="status">{copyState.message}</p>}<p className="vietqr-disclaimer">Quét QR không tự động đánh dấu khoản phí đã thanh toán. Admin vẫn cần đối soát và ghi nhận.</p></>}</>}
  </section></div>;
}

function LandmarkFallback() { return <WalletCards aria-hidden="true" />; }

export function FundsView({ team, permissions, result, paymentSettings, initialDialog }: { team: TeamAccessContext["team"]; permissions: readonly PermissionCode[]; result: FundsResult; paymentSettings: TeamPaymentSettings | null; initialDialog?: "entry" }) {
  const [dialog, setDialog] = useState<Dialog | null>(initialDialog === "entry" ? { kind: "entry" } : null); const [showAllTransactions, setShowAllTransactions] = useState(false); const [showQr, setShowQr] = useState(false); const canManage = hasPermission({ permissions }, "finance.manage");
  if (!result.ok) return <div className="view-stack funds-view funds-state" data-state="error"><section className="card"><h2>Không thể tải quỹ đội</h2><p>Kết nối dữ liệu đang gián đoạn. Vui lòng tải lại trang.</p></section></div>;
  const { data } = result; const empty = data.dues.length === 0 && data.recentEntries.length === 0; const pendingDues = data.dues.filter((due) => due.status === "pending"); const percent = data.totalDuesCount ? Math.round(data.paidDuesCount / data.totalDuesCount * 100) : 0; const visibleEntries = showAllTransactions ? data.recentEntries : data.recentEntries.slice(0, 4); const monthlyDelta = data.monthIncomeVnd - data.monthExpenseVnd; const monthlyDeltaTone = monthlyDelta > 0 ? "is-positive" : monthlyDelta < 0 ? "is-negative" : "is-neutral";
  return <div className="view-stack funds-view" data-state={empty ? "empty" : "ready"}>
    <section className="funds-hero-grid"><article className="balance-card black-sport-card"><span>SỐ DƯ KHẢ DỤNG</span><strong>{formatVnd(data.balanceVnd)}</strong><div className="fund-balance-delta"><b className={`fund-balance-change ${monthlyDeltaTone}`}><Coins /> {formatVnd(monthlyDelta)}</b><small>thay đổi trong tháng này</small></div><div className="vietqr-trigger-row"><button type="button" className="vietqr-btn" onClick={() => setShowQr(true)}><QrCode size={17} /> Quét mã VietQR nộp quỹ</button></div><WalletCards /></article>{canManage && <article className="fund-actions"><button onClick={() => setDialog({ kind: "entry" })}><span className="fund-action-icon"><HandCoins /></span><span className="fund-action-copy"><b>Thêm khoản chi</b><small>Ghi nhận chi phí mới</small></span></button><button className="lime-action" disabled={pendingDues.length === 0 && data.dueCandidates.length === 0} onClick={() => setDialog({ kind: "payment" })}><span className="fund-action-icon"><CreditCard /></span><span className="fund-action-copy"><b>Ghi nhận đóng quỹ</b><small>Cập nhật phí thành viên</small></span></button></article>}</section>
    <section className="fund-stats"><article><Coins /><span>THU THÁNG NÀY<strong>{formatVnd(data.monthIncomeVnd)}</strong><small>{data.monthIncomeCount} khoản đã ghi nhận</small></span></article><article><CircleDollarSign /><span>CHI THÁNG NÀY<strong>{formatVnd(data.monthExpenseVnd)}</strong><small>{data.monthExpenseCount} giao dịch</small></span></article><article><Clock3 /><span>ĐANG CHỜ<strong>{data.pendingDuesCount} người</strong><small>{formatVnd(data.pendingDuesVnd)} chưa thu</small></span></article></section>
    <section className="two-col fund-content-grid"><article className="card dues-card"><div className="section-head"><div><span>{monthName(data.periodStart)}</span><h2>Phí thành viên</h2></div><strong>{data.paidDuesCount}/{data.totalDuesCount}</strong></div><div className="dues-progress"><i style={{ width: `${percent}%` }} /></div>{data.dues.length === 0 ? <div className="fund-empty-copy"><h3>Chưa có dữ liệu quỹ</h3><p>Chưa có phí thành viên trong tháng này.</p></div> : data.dues.map((due) => <DueRow key={due.id} slug={team.slug} due={due} canManage={canManage} onVoid={() => setDialog({ kind: "voidPayment", due })} />)}{pendingDues.length > 0 && <ReminderControl periodStart={data.periodStart} dues={pendingDues} />}</article>
      <article className="card transactions-card"><div className="section-head"><div><span>DÒNG TIỀN</span><h2>Giao dịch gần đây</h2></div>{data.recentEntries.length > 4 && <button type="button" onClick={() => setShowAllTransactions((current) => !current)}>{showAllTransactions ? "Thu gọn" : "Xem tất cả"} →</button>}</div>{visibleEntries.length === 0 ? <div className="fund-empty-copy"><h3>Chưa có dữ liệu quỹ</h3><p>Chưa có giao dịch.</p></div> : visibleEntries.map((entry) => <div className="transaction" key={entry.id}><span>{entry.direction === "income" ? <CreditCard /> : entry.category.toLocaleLowerCase("vi-VN").includes("sân") ? <MapPin /> : <Trophy />}</span><div><b>{entry.description}</b><small>{formatDate(entry.occurredOn)} • {entry.category}</small></div><strong className={entry.direction === "income" ? "income" : ""}>{entry.direction === "income" ? "+" : "−"}{formatVnd(entry.amountVnd)}</strong>{canManage && entry.category !== "member_due" && <button className="fund-void-action" onClick={() => setDialog({ kind: "voidEntry", entry })}>Hủy</button>}</div>)}</article></section>
    {dialog?.kind === "entry" && <EntryDialog slug={team.slug} close={() => setDialog(null)} />}{dialog?.kind === "payment" && <PaymentDialog slug={team.slug} data={data} close={() => setDialog(null)} />}{(dialog?.kind === "voidEntry" || dialog?.kind === "voidPayment") && <VoidDialog slug={team.slug} target={dialog} close={() => setDialog(null)} />}
    {showQr && <VietQrDialog slug={team.slug} paymentSettings={paymentSettings} dues={pendingDues} close={() => setShowQr(false)} />}
  </div>;
}
